AllCops:
  Exclude:
    - '*.gemspec'
    - 'Vagrantfile'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

StringLiterals:
  EnforcedStyle: double_quotes

Style/FileName:
  Enabled: false
